
--PART 2: TRIGGER
ALTER TRIGGER A9
ON	LGLINE
AFTER	INSERT, DELETE, UPDATE
AS
BEGIN
	DECLARE @INV_NUM INT
	DECLARE @TOTAL INT

	--INSERT CASE
	IF (EXISTS (SELECT * FROM INSERTED) AND
		NOT EXISTS (SELECT * FROM DELETED))
	BEGIN
		DECLARE INSERTED_CURSOR CURSOR FOR
		SELECT	INV_NUM, SUM(LINE_QTY*LINE_PRICE) AS TOTAL
		FROM	INSERTED
		GROUP BY INV_NUM

		OPEN	INSERTED_CURSOR
		FETCH	NEXT FROM INSERTED_CURSOR
				INTO @INV_NUM, @TOTAL
		WHILE(@@FETCH_STATUS = 0)
		BEGIN
			UPDATE	LGINVOICE
			SET		INV_TOTAL = INV_TOTAL + @TOTAL
			WHERE	INV_NUM = @INV_NUM
			FETCH	NEXT FROM INSERTED_CURSOR
					INTO @INV_NUM, @TOTAL
		END
		CLOSE	INSERTED_CURSOR
		DEALLOCATE	INSERTED_CURSOR
	END

	--DELETE CASE
	ELSE IF (EXISTS (SELECT * FROM DELETED) AND
			 NOT EXISTS (SELECT * FROM INSERTED))
	BEGIN
		DECLARE	DELETE_CURSOR CURSOR FOR
		SELECT	INV_NUM, SUM(LINE_QTY*LINE_PRICE) AS TOTAL
		FROM	DELETED
		GROUP BY INV_NUM

		OPEN	DELETE_CURSOR
		FETCH	NEXT FROM DELETE_CURSOR INTO @INV_NUM, @TOTAL
		WHILE	(@@FETCH_STATUS = 0)
		BEGIN
			UPDATE	LGINVOICE
			SET		INV_TOTAL = INV_TOTAL - @TOTAL
			WHERE	INV_NUM = @INV_NUM
			FETCH	NEXT FROM DELETE_CURSOR INTO @INV_NUM, @TOTAL
		END
		CLOSE	DELETE_CURSOR
		DEALLOCATE	DELETE_CURSOR
	END

	--UPDATE CASE
	ELSE IF (EXISTS (SELECT * FROM INSERTED) AND
			 EXISTS (SELECT * FROM DELETED))
	BEGIN
		DECLARE UPDATE_CURSOR CURSOR FOR
		SELECT	I.INV_NUM, SUM((I.LINE_QTY * I.LINE_PRICE) - (D.LINE_QTY * D.LINE_PRICE)) AS TOTAL
		FROM	DELETED D INNER JOIN INSERTED I ON D.INV_NUM = I.INV_NUM
		GROUP BY I.INV_NUM

		OPEN	UPDATE_CURSOR
		FETCH	NEXT FROM UPDATE_CURSOR INTO @INV_NUM, @TOTAL
		WHILE	(@@FETCH_STATUS = 0)
		BEGIN
			UPDATE	LGINVOICE
			SET		INV_TOTAL = INV_TOTAL + @TOTAL
			WHERE	INV_NUM = @INV_NUM
			FETCH	NEXT FROM UPDATE_CURSOR INTO @INV_NUM, @TOTAL
		END
		CLOSE	UPDATE_CURSOR
		DEALLOCATE	UPDATE_CURSOR
	END
END

--PART 3: TEST CODE

--HOLD VALUES TO BE INSERTED INTO LGLINE AFTER THEY ARE DELETED
SELECT	* INTO LGLINE_TEST
FROM	LGLINE
WHERE	INV_NUM IN (110, 111, 112)

SELECT	*
FROM	LGINVOICE
WHERE	INV_NUM IN (110, 111, 112)

SELECT	*
FROM	LGLINE
WHERE	INV_NUM IN (110, 111, 112)

SELECT	*
FROM	LGLINE_TEST

--DELETE TEST
DELETE
FROM	LGLINE
WHERE	INV_NUM IN (110,111,112)

--INSERT TEST
INSERT INTO LGLINE
SELECT	*
FROM	LGLINE_TEST

--UPDATE TEST
UPDATE	LGLINE
SET		LINE_QTY = LINE_QTY + 10
WHERE	INV_NUM IN (110, 111, 112)
