--A10 PART B-B STORED PROCEDURE
CREATE PROCEDURE A10B
AS
BEGIN
SET NOCOUNT ON

--DROP CONSTRAINTS
ALTER TABLE FACT
DROP CONSTRAINT FK_FACT_PRODUCT, FK_FACT_TIME, FK_FACT_CUSTOMER, FK_FACT_EMPLOYEE

TRUNCATE TABLE PRODUCTDIM
TRUNCATE TABLE TIMEDIM
TRUNCATE TABLE CUSTOMERDIM
TRUNCATE TABLE FACTDIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_PRODUCT FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTDIM(PRODUCTID),
	CONSTRAINT FK_FACT_TIME FOREIGN KEY (TIMEID) REFERENCES TIMEDIM(TIMEID),
	CONSTRAINT FK_FACT_CUSTOMER FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDIM(CUSTOMERID),
	CONSTRAINT FK_FACT_EMPLOYEE FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEDIM(EMPLOYEEID)

--POPULATE DIMENSIONS WITH TRANSACTION DATA
INSERT INTO PRODUCTDIM
SELECT	P.PROD_SKU, P.PROD_DESCRIPT, P.PROD_TYPE, P.BRAND_ID, B.BRAND_NAME, B.BRAND_TYPE
FROM	LGPRODUCT P INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID

INSERT INTO TIMEDIM
SELECT	INV_DATE, YEAR(INV_DATE), MONTH(INV_DATE), DATEPART(QUARTER, INV_DATE)
FROM	LGINVOICE
GROUP BY INV_DATE

INSERT INTO CUSTOMERDIM
SELECT	CUST_CODE, CUST_FNAME, CUST_LNAME, CUST_CITY, CUST_STATE, CUST_ZIP
FROM	LGCUSTOMER

INSERT INTO EMPLOYEEDIM
SELECT	E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, E.EMP_TITLE, E.DEPT_NUM, D.DEPT_NAME
FROM	LGEMPLOYEE E INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM

--CREATE STAGING TABLE
CREATE TABLE STAGING
(
	PRODUCTID INT,
	TIMEID INT,
	CUSTOMERID INT,
	EMPLOYEEID INT,
	PROD_SKU VARCHAR(15),
	INV_DATE DATETIME,
	CUST_CODE INT,
	EMP_NUM INT,
	LINE_QTY INT,
	LINE_PRICE INT
)

INSERT INTO STAGING (PROD_SKU, INV_DATE, CUST_CODE, EMP_NUM, LINE_QTY, LINE_PRICE)
SELECT	P.PROD_SKU, I.INV_DATE, C.CUST_CODE, E.EMP_NUM, L.LINE_QTY, L.LINE_PRICE
FROM	LGINVOICE I INNER JOIN LGCUSTOMER C ON I.CUST_CODE = C.CUST_CODE
		INNER JOIN LGEMPLOYEE E ON I.EMPLOYEE_ID = E.EMP_NUM
		INNER JOIN LGLINE L ON I.INV_NUM = L.INV_NUM
		INNER JOIN LGPRODUCT P ON L.PROD_SKU = P.PROD_SKU

UPDATE STAGING
SET		S.PRODUCTID = P.PRODUCTID
FROM	STAGING S INNER JOIN PRODUCTDIM P ON S.PRODUCTID = P.PRODUCTID

UPDATE STAGING
SET		S.TIMEID = T.TIMEID
FROM	STAGING S INNER JOIN TIMEDIM T ON S.TIMEID = T.TIMEID

UPDATE STAGING
SET		S.CUSTOMERID = C.CUSTOMERID
FROM	STAGING S INNER JOIN CUSTOMERDIM C ON S.CUSTOMERID = C.CUSTOMERID

UPDATE STAGING
SET		S.EMPLOYEEID = E.EMPLOYEEID
FROM	STAGING S INNER JOIN EMPLOYEEDIM E ON S.EMPLOYEEID = E.EMPLOYEEID
 
--POPULATE FACT TABLE
INSERT INTO FACT (PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID, LINE_QTY, LINE_PRICE)
SELECT	PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID, LINE_QTY, LINE_PRICE
FROM	STAGING

DROP TABLE STAGING

END
GO
