--A10 PART B-A
--CREATE TABLES
DROP TABLE FACT
DROP TABLE CUSTOMERDIM
DROP TABLE PRODUCTDIM
DROP TABLE TIMEDIM
DROP TABLE EMPLOYEEDIM

CREATE TABLE CUSTOMERDIM
(	CUSTOMERID INT IDENTITY PRIMARY KEY,
	CUST_CODE INT,
	CUST_FNAME VARCHAR(20),
	CUST_LNAME VARCHAR(20),
	CUST_CITY VARCHAR(50),
	CUST_STATE CHAR(2),
	CUST_ZIP CHAR(5)
)

CREATE TABLE PRODUCTDIM
(
	PRODUCTID INT IDENTITY PRIMARY KEY,
	PROD_SKU VARCHAR(15),
	PROD_DESCRIPT VARCHAR(255),
	PROD_TYPE VARCHAR(255),
	BRAND_ID INT,
	BRAND_NAME VARCHAR(100),
	BRAND_TYPE VARCHAR(20)
)

CREATE TABLE EMPLOYEEDIM
(
	EMPLOYEEID INT IDENTITY PRIMARY KEY,
	EMP_NUM INT,
	EMP_FNAME VARCHAR(20),
	EMP_LNAME VARCHAR(20),
	EMP_TITLE VARCHAR(45),
	DEPT_NUM INT,
	DEPT_NAME VARCHAR(50)
)

CREATE TABLE TIMEDIM
(
	TIMEID INT IDENTITY PRIMARY KEY,
	INV_DATE DATETIME,
	YEAR INT,
	MONTH INT,
	QUARTER INT
)


CREATE TABLE FACT
(
	PRODUCTID INT NOT NULL,
	TIMEID INT NOT NULL,
	CUSTOMERID INT NOT NULL,
	EMPLOYEEID INT NOT NULL,
	LINE_QTY INT,
	LINE_PRICE INT
)

--ALTER TABLES TO ADD KEYS
ALTER TABLE FACT
ADD CONSTRAINT PK_FACT PRIMARY KEY (PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID)

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_PRODUCT FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTDIM(PRODUCTID),
	CONSTRAINT FK_FACT_TIME FOREIGN KEY (TIMEID) REFERENCES TIMEDIM(TIMEID),
	CONSTRAINT FK_FACT_CUSTOMER FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDIM(CUSTOMERID),
	CONSTRAINT FK_FACT_EMPLOYEE FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEDIM(EMPLOYEEID)
