--A8 SOLUTION

--1. List the products with a list price greater than the average list price of all products.
SELECT	M.ITEMID, M.DESCRIPTION, M.LISTPRICE
FROM	PET..MERCHANDISE M
WHERE	M.LISTPRICE > (SELECT AVG(LISTPRICE) FROM PET..MERCHANDISE)
ORDER BY M.LISTPRICE DESC;

--2. Which merchandise items have an average sale price more than 50 percent higher than their average purchase cost?
CREATE VIEW AVERAGECOSTS AS 
SELECT	ItemID, AVG(COST) AS AVERAGECOST
FROM	PET..OrderItem
GROUP  BY ItemID

CREATE VIEW AVERAGESALES AS
SELECT	ItemID, AVG(SALEPRICE) AS AVERAGESALE
FROM	PET..SaleItem
GROUP  BY ItemID

SELECT	C.ITEMID, C.AVERAGECOST AS AVGCOST, S.AVERAGESALE AS AVGSALE
FROM	AVERAGECOSTS C INNER JOIN AVERAGESALES S ON C.ItemID = S.ItemID
WHERE	S.AVERAGESALE > 1.5*C.AVERAGECOST

--3. List the employees and their total merchandise sales expressed as a percentage of total merchandise sales for all employees.
SELECT	Employee.EMPLOYEEID, Employee.LASTNAME, SUM([QUANTITY]*[SALEPRICE]) AS TotalSales, 
		SUM([QUANTITY]*[SALEPRICE])/(SELECT SUM([SALEPRICE]*[QUANTITY]) FROM PET..Sale INNER JOIN PET..SaleItem ON SALE.SaleID = SaleItem.SaleID) AS PctSales
FROM	(PET..Employee INNER JOIN PET..Sale ON Employee.EmployeeID = Sale.EmployeeID) INNER JOIN PET..SaleItem ON Sale.SaleID = SaleItem.SaleID
GROUP BY Employee.EmployeeID, Employee.LastName
ORDER BY SUM([QUANTITY]*[SALEPRICE]) DESC

--4. On average, which supplier charges the highest shipping cost as a percent of the merchandise order total?
CREATE VIEW	Q4 AS
SELECT	OI.PONumber, SUM([Quantity]*[Cost]) AS OrderTotal
FROM	PET..OrderItem OI
GROUP BY OI.PONumber

SELECT 	S.SUPPLIERID, S.NAME, AVG([SHIPPINGCOST]/[ORDERTOTAL]) AS PctOfShippingCost
FROM	PET..Supplier S INNER JOIN PET..MerchandiseOrder MO ON S.SupplierID = MO.SupplierID
		INNER JOIN Q4 ON MO.PONumber = Q4.PONumber
GROUP BY S.SupplierID, S.Name
HAVING	AVG([SHIPPINGCOST]/[ORDERTOTAL]) = 
		(SELECT TOP 1 AVG([SHIPPINGCOST]/[ORDERTOTAL]) AS PctOfShippingCost
		 FROM	PET..Supplier S INNER JOIN PET..MerchandiseOrder MO ON S.SupplierID = MO.SupplierID
		 INNER JOIN Q4 ON MO.PONumber = Q4.PONumber
		 GROUP BY S.SupplierID, S.Name
		 ORDER BY AVG([SHIPPINGCOST]/[ORDERTOTAL]) DESC)

--5. Which customer has given us the most total money for animals and merchandise?
CREATE VIEW MTOTAL AS
SELECT	S.CUSTOMERID, SUM([QUANTITY]*[SALEPRICE]) AS MERTOTAL
FROM	PET..SALE S INNER JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
GROUP BY S.CUSTOMERID

CREATE VIEW ATOTAL AS
SELECT	S.CUSTOMERID, SUM(SA.SALEPRICE) AS ANITOTAL
FROM	PET..SALE S INNER JOIN PET..SALEANIMAL SA ON S.SALEID = SA.SALEID
GROUP BY S.CUSTOMERID

SELECT	C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, MT.MERTOTAL, ATO.ANITOTAL, MT.MERTOTAL + ATO.ANITOTAL AS GRANDTOTAL
FROM	MTOTAL MT INNER JOIN PET..CUSTOMER C ON MT.CUSTOMERID = C.CUSTOMERID
		INNER JOIN ATOTAL ATO ON ATO.CUSTOMERID = C.CUSTOMERID
WHERE	MT.MERTOTAL + ATO.ANITOTAL =
		(SELECT TOP 1 (MT.MERTOTAL + ATO.ANITOTAL)
		 FROM	MTOTAL MT INNER JOIN PET..CUSTOMER C ON MT.CUSTOMERID = C.CUSTOMERID
		 INNER JOIN ATOTAL ATO ON ATO.CUSTOMERID = C.CUSTOMERID
		 ORDER BY MT.MERTOTAL + ATO.ANITOTAL DESC
		)

--6. Which customers who bought more than $100 in merchandise in May also spent more than $50 on merchandise in October?
SELECT	S.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, SUM([SALEPRICE]*[QUANTITY]) AS MAYTOTAL
FROM	PET..CUSTOMER C INNER JOIN PET..SALE S ON C.CUSTOMERID = S.CUSTOMERID
		INNER JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
WHERE	(((S.SALEDATE) BETWEEN '5/1/2004' AND '5/31/2004') AND
		((C.CUSTOMERID) IN
		(SELECT S.CUSTOMERID
		 FROM PET..SALE S INNER JOIN PET..SALEITEM SI ON S.SaleID = SI.SaleID
		 WHERE (S.SALEDATE BETWEEN '10/1/2004' AND '10/31/2004')
		 GROUP BY S.CustomerID
		 HAVING (SUM([SALEPRICE]*[QUANTITY]) > 50) )))
GROUP BY S.CustomerID, C.LASTNAME, C.FIRSTNAME
HAVING	(((SUM([SALEPRICE]*[QUANTITY])) > 100))

--7. What was the net change in quantity on hand for premium canned dog food between January 1 and July 1?
CREATE VIEW PURCHASED AS
SELECT	M.DESCRIPTION, OI.ITEMID, SUM(OI.QUANTITY) AS PURCHASED
FROM	PET..MerchandiseOrder MO INNER JOIN PET..ORDERITEM OI ON MO.PONUMBER = OI.PONUMBER
		INNER JOIN PET..MERCHANDISE M ON M.ITEMID = OI.ITEMID
WHERE	MONTH(MO.ORDERDATE) BETWEEN 1 AND 6
GROUP BY M.DESCRIPTION, OI.ITEMID
HAVING	M.Description = 'Dog Food-Can-Premium'

CREATE VIEW SOLD AS
SELECT	M.DESCRIPTION, M.ITEMID, SUM(SI.QUANTITY) AS SOLD
FROM	PET..Merchandise M INNER JOIN PET..SaleItem SI ON M.ItemID = SI.ItemID
		INNER JOIN PET..Sale S ON S.SaleID = SI.SaleID
WHERE	MONTH(S.SALEDATE) BETWEEN 1 AND 6
GROUP BY M.Description, M.ItemID
HAVING	M.Description = 'Dog Food-Can-Premium'

SELECT	P.DESCRIPTION, P.ITEMID, P.PURCHASED, S.SOLD, [PURCHASED] - [SOLD] AS NetIncrease
FROM	PURCHASED P INNER JOIN SOLD S ON P.ItemID = S.ItemID

--8. Which are the merchandise items with a list price of more than $50 and no sales in July?
SELECT	M.ITEMID, M.DESCRIPTION, M.LISTPRICE
FROM	PET..Merchandise M
WHERE	(M.LISTPRICE > 50) AND M.ItemID NOT IN
		(SELECT SI.ITEMID
		 FROM	PET..SALE S INNER JOIN PET..SALEITEM SI ON S.SaleID = SI.SaleID
		 WHERE	MONTH(S.SALEDATE) = 7
		 )

--9. Which merchandise items with more than 100 units on hand have not been ordered in 2004? Use an outer join to answer the question.
CREATE VIEW ITEMS2004 AS
SELECT	DISTINCT OI.ITEMID
FROM	PET..ORDERITEM OI INNER JOIN PET..MerchandiseOrder MO ON OI.PONumber = MO.PONumber
WHERE	YEAR(MO.ORDERDATE) = 2004

SELECT	M.ITEMID, M.DESCRIPTION, M.QUANTITYONHAND, I04.ITEMID
FROM	ITEMS2004 I04 RIGHT JOIN PET..Merchandise M ON M.ItemID = I04.ITEMID
WHERE	M.QUANTITYONHAND > 100 AND I04.ITEMID IS NULL

--10. Which merchandise items with more than 100 units on hand have not been ordered in 2004? Use a subquery to answer the question.
SELECT	M.ITEMID, M.DESCRIPTION, M.QUANTITYONHAND
FROM	PET..Merchandise M
WHERE	M.QuantityOnHand > 100 AND M.ITEMID NOT IN 
		(SELECT DISTINCT OI.ITEMID
		 FROM	PET..OrderItem OI INNER JOIN PET..MerchandiseOrder MO ON OI.PONumber = MO.PONumber
		 WHERE YEAR(MO.ORDERDATE) = 2004
		 )

--12. List all suppliers (animals and merchandise) who sold us items in June. Identify whether they sold use animals or merchandise.
SELECT	S.NAME, 'ANIMAL' AS ORDERTYPE
FROM	PET..Supplier S INNER JOIN PET..AnimalOrder A ON S.SupplierID = A.SupplierID
WHERE	MONTH(ORDERDATE) = 6
UNION
SELECT	S.NAME, 'MERCH' AS ORDERTYPE
FROM	PET..Supplier S INNER JOIN PET..MerchandiseOrder M ON S.SupplierID = M.SupplierID
WHERE	MONTH(ORDERDATE) = 6


